#!/bin/bash

trap umount_chroot HUP INT QUIT TERM SIGHUP SIGINT SIGQUIT SIGILL SIGABRT SIGKILL SIGTRAP SIGTERM SIGSTOP SIGSEGV

msg() {
	printf '[\033[32m INFO\033[m ] %s\n' "$@"
}

fail() {
	printf '[\033[31m FAIL\033[m ] %s\n' "$@"
	exit 1
}

mount_chroot() {
	msg "Mounting chroot..."
	mount -v --bind /dev $ROOTFS_DIR/dev
	mount -vt devpts devpts $ROOTFS_DIR/dev/pts -o gid=5,mode=620
	mount -vt proc proc $ROOTFS_DIR/proc
	mount -vt sysfs sysfs $ROOTFS_DIR/sys
	mount -vt tmpfs tmpfs $ROOTFS_DIR/run
	msg "Done mounting chroot."
}

umount_chroot() {
	msg "Unmounting chroot..."
	umount -v $ROOTFS_DIR/dev/pts
	umount -v $ROOTFS_DIR/dev
	umount -v $ROOTFS_DIR/run
	umount -v $ROOTFS_DIR/proc
	umount -v $ROOTFS_DIR/sys
	msg "Done unmounting chroot."
}

if [ $1 == "" ]; then
	fail "No rootfs directory has been specified"
fi

if [ ! -d "$1" ]; then
	fail "$1 is not a directory."
fi

ROOTFS_DIR=$1

mount_chroot

chroot "$ROOTFS_DIR" /usr/bin/env -i \
	HOME=/ \
	TERM="$TERM" \
	LC_ALL=POSIX \
	MAKEFLAGS="-j2" \
	PS1='(bdk_chroot)$ ' \
	PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/bash --login +h

umount_chroot

exit 0
