#!/bin/bash

set -e

msg() {
	printf '[\033[32m INFO\033[m ] %s\n' "$@"
}

fail() {
	printf '[\033[31m FAIL\033[m ] %s\n' "$@"
	exit 1
}

if [ -z "$BUILD_ARCH" ]; then
      fail "BUILD_ARCH is not set."
fi

if [ -d "$PWD/BUILD_DIR.$BUILD_ARCH" ]; then
      fail "$PWD/BUILD_DIR.$BUILD_ARCH does not exist."
fi

if [ -d "$PWD/BUILD_DIR.$BUILD_ARCH/packages" ]; then
      fail "$PWD/BUILD_DIR.$BUILD_ARCH/packages does not exist."
fi

FILE_DATE=$(date +%Y%m%d_%H%M%S)

msg "Getting packages."

cd $PWD/BUILD_DIR.$BUILD_ARCH/packages && tar -zcvf $PWD/packages-$BUILD_ARCH-$FILE_DATE.tar.gz --exclude 'host-*' --exclude '*.stamp' *

msg "Done."

exit 0